# Generated by Django 6.1.1 on 2026-09-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='design',
            new_name='slug',
        )
    ]
