# Generated by Django 6.1.1 on 2026-10-01 08:00

from django.db import migrations

def create_templates(apps,schema_editor):
    Template = apps.get_model("cv_builder", "Template")

    templates = [
        {
            "name": "Professional",
            "slug": "professional",
            "description": "A clean professional CV template.",
        },
        {
            "name": "Modern",
            "slug": "modern",
            "description": "A modern CV template with a contemporary layout.",
        },
    ]

    for template_data in templates:
        Template.objects.get_or_create(
            slug=template_data["slug"],
            defaults=template_data,
        )

class Migration(migrations.Migration):

    dependencies = [
        ("cv_builder", "0004_education_is_current_experience_is_current"),
    ]

    operations = [
        migrations.RunPython(
            create_templates,
            migrations.RunPython.noop,
        ),
    ]