# Generated by Django 6.1.1 on 2026-10-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0005_seed_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='last_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
