# Generated by Django 6.1.1 on 2026-10-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0006_cv_last_saved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
