# Generated by Django 6.1.1 on 2026-10-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_builder", "0008_education_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="does_not_expire",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="certification",
            name="credential_id",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="certification",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
