# Generated by Django 6.1.1 on 2026-10-01 08:00

from django.db import migrations


def create_templates(apps, schema_editor):
    Template = apps.get_model("cv_builder", "Template")

    templates = [
        {
            "name": "Inkwell",
            "slug": "inkwell",
            "description": "Make a striking impression. This creative, single-column design features bold typography and numbered sections against a warm background—perfect for standing out in design or marketing roles.",
        },
        {
            "name": "Prism",
            "slug": "prism",
            "description": "Showcase your expertise visually. A highly creative two-column layout featuring a stunning edge-to-edge gradient header and dynamic visual skill meters to instantly highlight your proficiency.",
        },
        {
            "name": "Campus",
            "slug": "campus",
            "description": "Classic elegance meets modern readability. Campus delivers a highly structured layout with sophisticated crimson accents. Ideal for recent graduates, academics, and corporate professionals.",
        },
        {
            "name": "Sprout",
            "slug": "sprout",
            "description": "Kickstart your career. Designed specifically for juniors and interns, this crisp layout pulls your education and projects to the forefront, highlighted by vibrant purple skill chips.",
        },
        {
            "name": "Northstar",
            "slug": "northstar",
            "description": "Navigate your career progression. A premium two-column layout designed for senior professionals, featuring an expansive main column for extensive work history and a tinted sidebar for quick-glance qualifications.",
        },
        {
            "name": "Meridian",
            "slug": "meridian",
            "description": "Command authority. Tailored for executives and directors, this commanding single-column layout features an elegant centered serif header, distinguished navy accents, and a refined framed border.",
        },
    ]

    for template_data in templates:
        Template.objects.get_or_create(
            slug=template_data["slug"],
            defaults=template_data,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("cv_builder", "0009_certification_expiration_details"),
    ]

    operations = [
        migrations.RunPython(
            create_templates,
            migrations.RunPython.noop,
        ),
    ]