# Generated by Django 6.1.1 on 2026-10-09 08:45

from django.db import migrations, models
from django.db.models.functions import Lower


class Migration(migrations.Migration):
    dependencies = [
        ("cv_builder", "0010_batch2_seed_template_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="is_cv_copy",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveConstraint(
            model_name="skill",
            name="unique_skill_per_user",
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.UniqueConstraint(
                Lower("name"),
                "user",
                condition=models.Q(is_cv_copy=False),
                name="unique_skill_per_user",
            ),
        ),
    ]
