# Generated by Django 6.1.1 on 2026-10-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_builder', '0011_skill_cv_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='professional_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
